### ISSUE TITLE
Spolszczenie Settings i formatowanie opcji parsera

### ISSUE THREAD

**Issue by cnosko** [ikurek/PWr-App#10]
Po przejściu do ustawień wyświetlana nazwa zakładki na samej górze to 'Settings'  zamiast ustawienia. W reszcie zakładek jest ok.

**Comment by ikurek** [comment]
Hardcoded string w SettingsActivity, do zrobienia

**Comment by cnosko** [comment]
Oprócz tego poprawiłbym formatowanie opisu opcji wyboru parsera
![screenshot_2016-09-16-21-47-14](https://cloud.githubusercontent.com/assets/22050555/18599864/e1e90f5c-7c5a-11e6-9b3a-db5a3e959797.png)

**Comment by ikurek** [comment]
Sprawdź w poziomie bo nie wiem czy to za długi string czy zły layout tego rzędu

**Comment by cnosko** [comment]
![screenshot_2016-09-16-23-22-29](https://cloud.githubusercontent.com/assets/22050555/18601743/26886504-7c65-11e6-9147-305fd883d8cc.png)
w poziomie jest git

**Comment by ikurek** [comment]
Rozwiązane
