### ISSUE TITLE
Skrót nie przenosi do ustawień

### ISSUE THREAD

**Issue by cnosko** [ikurek/PWr-App#11]
Skrót do ustawień umieszczony w prawnym górnym rogu pod rozwijaną listą nadal nie reaguje na tapnięcia.

**Comment by ikurek** [comment]
Wywalić czy przypisać aktywność? Bo nie wiem sam :-D

**Comment by cnosko** [comment]
Może odświeżenie w tym miejscu?

**Comment by ikurek** [comment]
Odświeżenie czego?

**Comment by cnosko** [comment]
Parasola... :-D
Newsfeeda

**Comment by ikurek** [comment]
Ale on się odświeża jak klikniesz ponownie "Aktualności". Na razie podpinam ten skrót pod ustawienia, może potem dodam odświeżanie faktycznie.
