### ISSUE TITLE
Problem z przełącznikami stanu w ustawieniach

### ISSUE THREAD

**Issue by cnosko** [ikurek/PWr-App#14]
Przy przewijaniu listy wydziałów przełączniki cofaja się do poprzedniego stanu.  Żeby go zachowaly trzeba zatrzymać je na widoku, wyjść do ustawień i wejść jeszcze raz. Błąd występuje na androidzie 4.4.3

**Comment by ikurek** [comment]
A zapisuje się ich wciśnięcie? Bo nie wiem czy problem dotyczy layoutu czy coś źle w funkcji jest?

**Comment by cnosko** [comment]
Nie zapisuje się, żeby zapisać trzeba wyjść tak jak napisałem, nie przesuwając widoku.

**Comment by ikurek** [comment]
Zmieniono na PreferenceCheckBox, rozwiązane
