### ISSUE TITLE
Baza danych budynków

### ISSUE THREAD

**Issue by ikurek** [ikurek/PWr-App#16]
Potrzebuję bazy danych budynków zawierającej:

- Nazwę Budynku
- Adres budynku w formacie "%numer%, %ulica%, Wrocław"
- Szerokość geograficzną wejścia
- Długość geograficzną wejścia
- Główne elementy które się w tym budynku znajdują

**Comment by cnosko** [comment]
Aktualizacja - mam wszystkie adresy i z połowę współrzędnych.

**Comment by ikurek** [comment]
Zamknij issue jak baza danych będzie gotowa :-D
