### ISSUE TITLE
Nakładają się fragmenty przy transakcji z/na budynki

### ISSUE THREAD

**Issue by ikurek** [ikurek/PWr-App#2]
Czasami nakładają się na siebie layouty 2 fragmentów przy kliknięciu wstecz, chyba gdzieś brakuje addToBackStack() w transakcji, albo fragmenty nie są prawidłowo zamykane.

**Comment by nospa2137** [comment]
Potwierdzam, właśnie mi się nałożył layout ze zgłoś błąd na budynki po naciśnięciu wstecza. Ale to w sumie dziwne bo  widze ze ten wstecz raz przenosi  powrotem a raz wychodzi  z apki :-D

**Comment by ikurek** [comment]
Dzień 5123125251, dalej nie znalazłem błędu który to powoduje

**Comment by ikurek** [comment]
Wygląda na to że po posprzątaniu kodu i optymalizacji w wersji 5 problem przestał występować, uznaje za rozwiązane, najwyżej otworzy się issue ponownie.
