### ISSUE TITLE
Karty Chrome nie działają 

### ISSUE THREAD

**Issue by cnosko** [ikurek/PWr-App#21]
Na androidzie 4.4.3 nie działają karty Chrome, otwiera linki w przeglądarce.

**Comment by ikurek** [comment]
A masz Chrome zainstalowane?

**Comment by cnosko** [comment]
Nie używam Chrome'a, tak też myślałem, że to pewnie wina tego.

**Comment by ikurek** [comment]
Czyli jest wszystko okej, jak masz Chrome to otwiera w karcie, jak nie masz to w przeglądarce. Dodam jakiś checker do tego żeby to zaznaczyć.

**Comment by cnosko** [comment]
Aczkolwiek pomyślałbym o pobieraniu treści artykułu i wyswietlaniu w apce zamiast całej strony

**Comment by ikurek** [comment]
It's not a bug, it's a feature!
