### ISSUE TITLE
Dodanie aktualnie granej piosenki w Radiu Luz

### ISSUE THREAD

**Issue by cnosko** [ikurek/PWr-App#24]
Na stronie radia jest możliwość sprawdzenia aktualnie granej piosenki,  dobrze by bylo jakby taka opcja się pojawiła.  Można by było też połączyć to z powiadomieniem na pasku.

**Comment by ikurek** [comment]
Problem jest taki że to jest w jakiś sposób wrzucone w animację we flashu. Musiał bym znaleźć sposób żeby to wciągnąć (raczej niemożliwe), albo ustalić skąd ten flash bierze informacje.
