### ISSUE TITLE
Radio nie wznawia działania po połączeniu wychodzącym

### ISSUE THREAD

**Issue by cnosko** [ikurek/PWr-App#26]
Jak w tytule, jeżeli ktoś zadzwoni wszystko działa, lecz jeżeli my zadzwonimy to nie włącza się z powrotem.

**Comment by ikurek** [comment]
Myślałem że taka opcja będzie sensowniejsza, więc to nie bug. Myślisz że powinno się odpalać ponownie?

**Comment by cnosko** [comment]
Skoro jeśli ktoś do Ciebie dzwoni i odpala się ponownie to myślę że w drugą stronę też tak powinno być, mnie przynajmniej denerwowalo jak musiałem odpalić muzykę znowu po połączeniu

**Comment by ikurek** [comment]
Zaakceptowane, zaimplementowano
