### ISSUE TITLE
Powiadomienie Radia

### ISSUE THREAD

**Issue by cnosko** [ikurek/PWr-App#29]
2 problemy na tę chwilę. 
1. Po tapnieciu powiadomienia na pasku, przechodzi do strony głównej apki czyli aktualności zamiast radia
2. Kontrolka stopu nie działa jeśli puścimy radio i wyjdziemy gdziekolwiek lub zminimalizujemy appke. Po powrocie nie da się radia zatrzymać, a jak damy jeszcze raz play, to dwa streamy się nakładają i stop zadziała i tak tylko dla tego dopiero włączonego.

**Comment by ikurek** [comment]
W najnowszej wersji usuwam ten player totalnie, zamiast niego dodam informacje o wydziałach itd

**Comment by cnosko** [comment]
Ale ten player w wersji 7 bardzo ładnie działał

**Comment by ikurek** [comment]
Nie działał w tle, znaczy że z czasem zjadł by ci ram i pamięć. A jak jest w tle to jest z nim tyle problemów że nie warto się z tym bawić
