### ISSUE TITLE
Niewłaściwe podświetlanie otwartych zakładek

### ISSUE THREAD

**Issue by cnosko** [ikurek/PWr-App#3]
Po przejściu z np. kotów do Wydziałów, w menu są podświetlone koty mimo wyświetlenia zakładki wydziałowej.

**Comment by ikurek** [comment]
Okay, nie wiem czemu dalej. Poszukam.

**Comment by cnosko** [comment]
Błąd częściowo poprawiony, występuje nadal tylko przy zakładkach 'O aplikacji'  oraz 'Kontakt/zgłoszenie błędu'.

**Comment by cnosko** [comment]
Częściowo nadal występuje przy cofnięciu przyciskiem wstecz

**Comment by ikurek** [comment]
Problem z grupami w xml. Rozwiązane.
