### ISSUE TITLE
Przewijanie listy społeczności 

### ISSUE THREAD

**Issue by cnosko** [ikurek/PWr-App#31]
Nie da się przewinac listy społeczności w dół, a widać, że jeszcze przynajmniej jedna pozycja jest niżej.

**Comment by cnosko** [comment]
![screenshot_2016-09-29-23-07-28](https://cloud.githubusercontent.com/assets/22050555/18973716/324660e6-869f-11e6-8213-9a1107021603.png)
![screenshot_2016-09-29-23-09-51](https://cloud.githubusercontent.com/assets/22050555/18973717/324b598e-869f-11e6-9900-e449955bf61a.png)

**Comment by ikurek** [comment]
fikseddddddd
